Parameters:
  DBUserName:
    Type: String
    Default: admin
    Description: The Drupal database admin account username
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    Type: String
    Default: password
    NoEcho: 'true'
    Description: The DB admin account password
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.
  DBName:
    Type: String
    Default: drizzle
    Description: The  database name
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
Resources:
  MyDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "description"
      SubnetIds:
        - !ImportValue PrivateSubnet1
        - !ImportValue PrivateSubnet2
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.micro
      MultiAZ: true
      Engine: MySQL
      DBName: !Ref DBName
      MasterUsername: !Ref DBUserName
      MasterUserPassword: !Ref DBPassword
      DBSecurityGroups:
        - Ref: DBSecurityGroup
    DeletionPolicy: Snapshot

  DBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      EC2VpcId: !ImportValue VPC
      DBSecurityGroupIngress:
        - CIDRIP: !ImportValue PrivateSubnetCIDR1
        - CIDRIP: !ImportValue PrivateSubnetCIDR2
      GroupDescription: Frontend Access
Outputs:
  DBEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt MyDB.Endpoint.Address
    Export:
      Name: DBEndpoint
  MyDBUserName:
    Description: DB UserName
    Value: !Ref DBUserName
    Export:
      Name: DBUserName
  MyDBName:
    Description: DB Instance Name
    Value: !Ref DBName
    Export:
      Name: DBName
